myFile = open("CSVFile.csv","wb")
myFile.write("Name,")
myFile.write("Phone,")
myFile.write("Email,")
myFile.write("Town\n")
myFile.write("John,")
myFile.write("203-465-6465,")
myFile.write("johnfknight@gmail.com,")
myFile.write("Fairfield\n")
myFile.write("JFK Quality,")
myFile.write("203-ImJohnK,")
myFile.write("jfkquality@gmail.com,")
myFile.write("Qualiity Town\n")
myFile.write("John Checkmate,")
myFile.write("203-259-2765,")
myFile.write("john@checkmate.digital,")
myFile.write("Hamden\n")
myFile.write("JFK Checkmate,")
myFile.write("203-255-4451,")
myFile.write("jfk@checkmate.digital,")
myFile.write("Hamden\n")
myFile.close()
